apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: agitated-grothendieck-3c8001
spec:
    name: client-services
    retentionRules:
      - everySeconds: 2.592e+06
        type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: festive-swanson-3c8003
spec:
    charts:
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: "y"
            scale: linear
        colors:
          - hex: '#31C0F6'
            id: f71d2d7e-dc49-4260-ba1c-eaadff491e9e
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            id: 8d7bc01a-9115-4bfe-8d00-c766396be660
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            id: 2770d862-5a71-49c6-b703-6a61e25b48b8
            name: Nineteen Eighty Four
            type: scale
        geom: step
        height: 4
        hoverDimension: auto
        kind: Xy
        legendColorizeRows: true
        legendOpacity: 1
        legendOrientationThreshold: 1e+08
        name: peers
        position: overlaid
        queries:
          - query: |-
                from(bucket: "client-services")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "membership" or r["_measurement"] == "peers")
                  |> filter(fn: (r) => r["_field"] == "active" or r["_field"] == "connected" or r["_field"] == "passive")
                  |> filter(fn: (r) => r["peer_id"] == "hyyqpngdoe4x4oto3emfdppbw7sj1pfaghbpmmhz5rqiuqg8uofmeo")
                  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
                  |> yield(name: "last")
        width: 5
        xCol: _time
        yCol: _value
    name: org-node

