query AllProjects($timestamp: BigInt!) {
    projects(where: {
        timestamp_gt: $timestamp,
    }, orderBy: timestamp) {
        timestamp
        org { id }
        anchor { objectId, multihash }
    }
}
