query OrgProjects($timestamp: BigInt!, $orgs: [ID]!) {
    projects(where: {
        timestamp_gt: $timestamp,
        org_in: $orgs,
    }, orderBy: timestamp) {
        timestamp
        org { id }
        anchor { objectId, multihash }
    }
}
